version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    #NGINX
    nginx:
        image: nginx:alpine
        container_name: scrabble-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes: 
            - ./:/var/www/app
            - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - db
        networks: 
            - laravel
    # DB
    db:
        platform: linux/amd64
        image: mysql
        container_name: scrabble-mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${DB_EXTERNAL_PORT}:3306"
        volumes: 
            - ./docker-compose/mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks: 
            - laravel
    #APP
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scrabble-php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./:/var/www/app
        ports: 
            - "${APP_EXTERNAL_PORT}:80"
            - "${APP_EXTERNAL_PORT_SSL}:443"
        networks: 
            - laravel
